#include <float.h>
#include <stdbool.h>

#include "util/distributions.h"
#include "util/errors.h"

#define SAMPLES_COUNT 1000000
#define QUANTS_COUNT 100
#define ACCURACY 0.001          // 0.1 % accuracy

void test_random_distribution_mean()
{
    double samples[SAMPLES_COUNT], accumulator = 0;

    // fill the samples array with number generated by the function
    for (int i = 0; i < SAMPLES_COUNT; i++)
    {
        accumulator += samples[i] = normal_random(0.0f, 1.0f);
    }

    // get the average value of the array
    accumulator /= SAMPLES_COUNT;

    // check that the average is the mean of the distribution
    assert(
        -ACCURACY <= accumulator && accumulator <= ACCURACY, -1,
        "The mean of the distribution is %f instead of 0", accumulator
    );

    // reset the accumulator
    accumulator = 0;

    // fill the samples array with number generated by the function
    for (int i = 0; i < SAMPLES_COUNT; i++)
    {
        accumulator += samples[i] = normal_random(100.0f, 1.0f);
    }

    // get the average value of the array
    accumulator /= SAMPLES_COUNT;

    // check that the average is the mean of the distribution
    assert(
        100 * (1 - ACCURACY) <= accumulator && accumulator <= 100 * (1 + ACCURACY),
        -1, "The mean of the distribution is %f instead of 100", accumulator
    );
}

void test_random_distribution_shape()
{
    double samples[SAMPLES_COUNT], min = FLT_MAX, max = FLT_MIN;

    // fill the samples array with number generated by the function
    for (int i = 0; i < SAMPLES_COUNT; i++)
    {
        samples[i] = normal_random(0.0f, 1.0f);
        if (samples[i] > max)
        {
            max = samples[i];
        }
        if (samples[i] < min)
        {
            min = samples[i];
        }
    }

    int discrete_samples[QUANTS_COUNT] = { 0 };

    // discretize the samples in 100 quants
    for (int i = 0; i < QUANTS_COUNT; i ++)
    {
        discrete_samples[(int)(QUANTS_COUNT * (samples[i] - min) / (max - min))]++;
    }

    // check that the bell shape is maintained
    for (int i = 0; i < QUANTS_COUNT - 1; i++)
    {
        // before index 50 the amount of entries should increase,
        // after index 50 the amount of entries should decrease
        // consider some possible errors: 5 over 1000000
        bool test = discrete_samples[i] - 5 <= discrete_samples[i + 1];
        if (i >= QUANTS_COUNT / 2)
        {
            test = discrete_samples[i] + 5 >= discrete_samples[i + 1];
        }
        assert(
            test, -1, "The distribution is not normal: #%d = %d, #%d = %d",
            i, discrete_samples[i], i + 1, discrete_samples[i + 1]
        );
    }
}

int util_distributions()
{
    test_random_distribution_mean();
    test_random_distribution_shape();

    return 0;
}
