name: Doxygen Action

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update cache
      run: apt-get update
    - name: Install doxygen
      run: apt-get install -y doxygen
    - name: Generate documentation
      run: doxygen Doxyfile

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
