name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set the doxygen-awesome submodule
        run: git submodule add https://github.com/jothepro/doxygen-awesome-css.git && cd cd doxygen-awesome-css && git checkout v2.3.3 && cd ..
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
